public enum UI_PANEL
{
    NONE,
    PopupConfirm,
    MainScreen,
    PopupSetting,
    VictoryScreen,
    DefeatScreen,
    ContinueScreen,
    PopupTutorial,
    PopupNoInternet,
    PopupWarning,
    PlayScreen,
    PopupUpgradeTool,
    PopupUnlockProgress,
    PopupShop,
    PopupOfflineReward,
    PopupOfferNoAds,
    HC_Place_Holder
}